### ISSUE TITLE
check_carbonara_nicole_by_Simone

### ISSUE THREAD

**Issue by SimoFari** [ArtesiaWater/GH_exercise#4]
[https://github.com/ArtesiaWater/GH_exercise/blob/main/carbonara_nicole.py](url)
the script doesn't work. maybe because:
regarding the ingredients it is necessary to replace the round brackets with square brackets

I have some notes on the ingredients, but... obviously it depends on people's personal tastes :)
1. I wouldn't add parmesan, garlic and butter
2. I prefer to used guanciale instead of pancetta

**Comment by TheEEMTeam** [comment]
Fixed!
