### ISSUE TITLE
Michele recepit...are you confused?

### ISSUE THREAD

**Issue by FedeFaso** [ArtesiaWater/GH_exercise#8]
hi Michele its Federico here
when do you use chopped sausage if you fry pancetta?
I don't mind pancetta instead of guanciale but the garlic?? really?
and the butter is unused (luckily I would say)
for the egg you only use yolk, I expected more from you
[carbonara_original_michele_ff.txt](https://github.com/ArtesiaWater/GH_exercise/files/15234346/carbonara_original_michele_ff.txt)

**Comment by mciaffa** [comment]
yes sir, 
I will solve all this problem to prepare the best carbonare you ever tried.
